<a href="https://colab.research.google.com/github/hansi-2000/HR-Project_ML/blob/main/Neural.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
## IMPORT LIBRARIES ##

import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.stats as stats

# Import the required function for preprocessing
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.compose import ColumnTransformer

# Import train and test split function
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split

# Import Classifiers to be used
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier

# Import packages to calculate performance of the models
from sklearn import metrics
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score, roc_auc_score

# To save the model import pickle
import pickle

In [2]:
import pandas as pd

# Train dataset
train_url = 'https://drive.google.com/uc?export=download&id=182IBfEbem0yc9OlrIFhKglxlEZmGgG5Z'
train = pd.read_csv(train_url)

# Test dataset
test_url = 'https://drive.google.com/uc?export=download&id=17fw8C110W-X0R18v_g0PsNGmGOH-wKIG'
test = pd.read_csv(test_url)

**LABEL** **ENCODING**

In [3]:
df = pd.concat([train, test])

In [4]:
df = df.drop("Employee ID", axis=1)
df = df.drop("Gender", axis=1)
df = df.drop("Job Role", axis=1)
df = df.drop("Company Tenure", axis=1)
#df = df.drop("Overtime", axis=1)
df = df.drop("Leadership Opportunities", axis=1)
df = df.drop("Innovation Opportunities", axis=1)

train = train.drop("Employee ID", axis=1)
train = train.drop("Gender", axis=1)
train = train.drop("Job Role", axis=1)
train = train.drop("Company Tenure", axis=1)
#train = train.drop("Overtime", axis=1)
train = train.drop("Leadership Opportunities", axis=1)
train = train.drop("Innovation Opportunities", axis=1)

test = test.drop("Employee ID", axis=1)
test = test.drop("Gender", axis=1)
test = test.drop("Job Role", axis=1)
test = test.drop("Company Tenure", axis=1)
#test = test.drop("Overtime", axis=1)
test = test.drop("Leadership Opportunities", axis=1)
test = test.drop("Innovation Opportunities", axis=1)

df.head(10)

# mms = MinMaxScaler()
# df = pd.DataFrame(mms.fit_transform(df), columns=df.columns)

,Age,Years at Company,Monthly Income,Work-Life Balance,Job Satisfaction,Performance Rating,Number of Promotions,Overtime,Distance from Home,Education Level,Marital Status,Number of Dependents,Job Level,Employee Recognition,Remote Work,Company Reputation,Attrition
0,57,5,8972,Good,Medium,Average,0,No,39,High School,Divorced,0,Entry,Low,Yes,Excellent,Stayed
1,57,3,9898,Fair,Low,Low,4,No,38,Master’s Degree,Married,0,Mid,High,No,Good,Stayed
2,47,18,3943,Fair,High,High,3,Yes,90,Bachelor’s Degree,Married,4,Senior,High,Yes,Good,Stayed
3,28,13,9682,Excellent,High,Average,0,No,72,Bachelor’s Degree,Married,1,Senior,Medium,No,Good,Stayed
4,48,27,5348,Good,Medium,Average,0,No,63,Master’s Degree,Married,3,Mid,High,No,Good,Left
5,36,23,5226,Poor,Very High,Average,0,No,17,Master’s Degree,Single,1,Mid,Low,No,Good,Left
6,37,9,6439,Good,Very High,Average,0,No,25,Bachelor’s Degree,Single,2,Entry,High,No,Poor,Left
7,56,17,8143,Excellent,Medium,High,0,No,18,Bachelor’s Degree,Married,3,Mid,High,No,Good,Stayed
8,19,3,3949,Excellent,High,Below Average,2,No,69,Master’s Degree,Single,3,Senior,High,No,Poor,Left
9,51,5,9560,Good,Low,Below Average,1,Yes,39,Master’s Degree,Married,3,Mid,Low,No,Poor,Left

In [5]:
def label_encoder(dataframe, binary_col):
    labelencoder = LabelEncoder()
    dataframe[binary_col] = labelencoder.fit_transform(dataframe[binary_col])
    return dataframe

In [6]:
binary_cols = [col for col in df.columns if df[col].dtype not in [int, float]
               and df[col].nunique() == 2]

In [7]:
for col in binary_cols:
    df = label_encoder(df, col)

**ONEHOT** **ENCODING**

In [8]:
def one_hot_encoder(dataframe, categorical_cols, drop_first=True):
    dataframe = pd.get_dummies(dataframe, columns=categorical_cols, drop_first=drop_first)
    return dataframe

In [9]:
ohe_cols = [col for col in df.columns if 10 >= df[col].nunique() > 2]

In [10]:
df = one_hot_encoder(df, ohe_cols, drop_first=True)

In [11]:
mms = MinMaxScaler()
df = pd.DataFrame(mms.fit_transform(df), columns=df.columns)
df.head()

,Age,Years at Company,Monthly Income,Overtime,Distance from Home,Remote Work,Attrition,Work-Life Balance_Fair,Work-Life Balance_Good,Work-Life Balance_Poor,...,Number of Dependents_5,Number of Dependents_6,Job Level_Mid,Job Level_Senior,Employee Recognition_Low,Employee Recognition_Medium,Employee Recognition_Very High,Company Reputation_Fair,Company Reputation_Good,Company Reputation_Poor
0,0.951220,0.08,0.500070,0.0,0.387755,1.0,1.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1,0.951220,0.04,0.564572,0.0,0.377551,0.0,1.0,1.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,0.707317,0.34,0.149763,1.0,0.908163,1.0,1.0,1.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
3,0.243902,0.24,0.549526,0.0,0.724490,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
4,0.731707,0.52,0.247632,0.0,0.632653,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [12]:

ordinal_mappings = {
    #'Work-Life Balance': {'Poor': 1, 'Fair': 2, 'Good': 3, 'Excellent': 4},
    #'Company Reputation': {'Poor': 1, 'Fair': 2, 'Good': 3, 'Excellent': 4},
    'Job Satisfaction': {'Low': 1, 'Medium': 2, 'High': 3, 'Very High': 4},
    'Performance Rating': {'Low': 1, 'Below Average': 2, 'Average': 3, 'High': 4},
    'Education Level': {'High School': 1, 'Associate Degree': 2, 'Bachelor’s Degree': 3, 'Master’s Degree': 4, 'PhD': 5},
    #'Job Level': {'Entry': 1, 'Mid': 2, 'Senior': 3},
    #'Company Reputation': {'Very Poor': 0, 'Poor': 1, 'Fair':2, 'Good': 3, 'Excellent': 4},
    #'Employee Recognition': {'Very Low': 0, 'Low': 1, 'Medium': 2, 'High': 3}
}


for col, mapping in ordinal_mappings.items():
    train[col] = train[col].map(mapping)
    test[col] = test[col].map(mapping)

In [13]:
df.head()

,Age,Years at Company,Monthly Income,Overtime,Distance from Home,Remote Work,Attrition,Work-Life Balance_Fair,Work-Life Balance_Good,Work-Life Balance_Poor,...,Number of Dependents_5,Number of Dependents_6,Job Level_Mid,Job Level_Senior,Employee Recognition_Low,Employee Recognition_Medium,Employee Recognition_Very High,Company Reputation_Fair,Company Reputation_Good,Company Reputation_Poor
0,0.951220,0.08,0.500070,0.0,0.387755,1.0,1.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1,0.951220,0.04,0.564572,0.0,0.377551,0.0,1.0,1.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,0.707317,0.34,0.149763,1.0,0.908163,1.0,1.0,1.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
3,0.243902,0.24,0.549526,0.0,0.724490,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
4,0.731707,0.52,0.247632,0.0,0.632653,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [ ]:
print(train.dtypes)

Employee ID                  int64
Age                          int64
Gender                      object
Years at Company             int64
Job Role                    object
Monthly Income               int64
Work-Life Balance           object
Job Satisfaction            object
Performance Rating          object
Number of Promotions         int64
Overtime                    object
Distance from Home           int64
Education Level             object
Marital Status              object
Number of Dependents         int64
Job Level                   object
Employee Recognition        object
Company Tenure               int64
Remote Work                 object
Leadership Opportunities    object
Innovation Opportunities    object
Company Reputation          object
Attrition                   object
dtype: object

In [ ]:
Q1 = train[train.columns].quantile(0.25)
Q3 = train[train.columns].quantile(0.75)
IQR = Q3 - Q1

# Detect outliers
outliers = ((train[train.columns] < (Q1 - 1.5 * IQR)) |
            (train[train.columns] > (Q3 + 1.5 * IQR))).any(axis=1)
print(f"Number of outliers: {outliers.sum()}")

TypeError: unsupported operand type(s) for -: 'str' and 'str'

In [ ]:
train = train[~outliers]

NameError: name 'outliers' is not defined

**Data Pre Proccessing**

In [14]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import tensorflow as tf

# Shuffle the combined dataset
df = df.sample(frac=1, random_state=42).reset_index(drop=True)

# Separate features and target variable
X = df.drop(columns=['Attrition'])  # Assuming 'Attrition' is the target column
y = df['Attrition']  # Assuming binary labels 'Stayed'/'Left' or 0/1

# Handle missing values if present
X = X.fillna(X.mean())

# Encode categorical variables if any
# If 'X' contains categorical variables, encode them using one-hot encoding
X = pd.get_dummies(X)

# Encode target variable if it's categorical
if y.dtype == 'object':
    y = y.map({'Stayed': 0, 'Left': 1})

# Convert 'y' to numpy array
y = y.values

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42)

# Feature Scaling
scaler = StandardScaler()
X_new = X_train
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [15]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(random_state=42)
rf.fit(X_train, y_train)

# Feature importances
importances = pd.Series(rf.feature_importances_, index=X_new.columns)
print(importances.sort_values(ascending=False))

Distance from Home                   0.102422
Monthly Income                       0.100804
Age                                  0.088756
Years at Company                     0.087523
Job Level_Senior                     0.072872
Marital Status_Single                0.058177
Remote Work                          0.048381
Job Level_Mid                        0.026978
Marital Status_Married               0.026105
Work-Life Balance_Fair               0.020623
Employee Recognition_Low             0.017782
Overtime                             0.017241
Work-Life Balance_Poor               0.016555
Education Level_Bachelor’s Degree    0.016514
Number of Promotions_1               0.016468
Employee Recognition_Medium          0.016288
Performance Rating_High              0.015637
Number of Dependents_1               0.015472
Job Satisfaction_Very High           0.014783
Education Level_High School          0.014484
Number of Promotions_2               0.014426
Education Level_Master’s Degree      0.014361
Job Satisfaction_Medium              0.014256
Company Reputation_Good              0.013833
Performance Rating_Below Average     0.013766
Number of Promotions_3               0.013318
Work-Life Balance_Good               0.012519
Number of Dependents_3               0.012441
Number of Dependents_2               0.012304
Number of Dependents_4               0.012279
Education Level_PhD                  0.012231
Company Reputation_Poor              0.012039
Company Reputation_Fair              0.010688
Job Satisfaction_Low                 0.010613
Performance Rating_Low               0.007409
Number of Dependents_5               0.006961
Employee Recognition_Very High       0.006745
Number of Promotions_4               0.003746
Number of Dependents_6               0.002199
dtype: float64

In [16]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

import warnings
warnings.filterwarnings('ignore')

model=Sequential()
model.add(Dense(87,activation='relu'))
model.add(Dense(76,activation='relu'))
model.add(Dense(64,activation='relu'))
model.add(Dense(53,activation='relu'))
model.add(Dense(46,activation='relu'))
model.add(Dense(35,activation='relu'))
model.add(Dense(24,activation='relu'))
model.add(Dense(12,activation='relu'))
model.add(Dense(9,activation='relu'))
model.add(Dense(4,activation='relu'))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [17]:
x = df.drop("Attrition", axis=1)
y = df[['Attrition']]
history = model.fit(x,y,epochs=50,batch_size=32,validation_split=.20,verbose=1)

Epoch 1/50
943/943 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - accuracy: 0.7072 - loss: 0.5588 - val_accuracy: 0.7551 - val_loss: 0.4817
Epoch 2/50
943/943 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - accuracy: 0.7551 - loss: 0.4795 - val_accuracy: 0.7540 - val_loss: 0.4775
Epoch 3/50
943/943 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - accuracy: 0.7580 - loss: 0.4759 - val_accuracy: 0.7442 - val_loss: 0.4851
Epoch 4/50
943/943 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - accuracy: 0.7537 - loss: 0.4739 - val_accuracy: 0.7513 - val_loss: 0.4840
Epoch 5/50
943/943 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.7605 - loss: 0.4663 - val_accuracy: 0.7556 - val_loss: 0.4798
Epoch 6/50
943/943 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - accuracy: 0.7574 - loss: 0.4696 - val_accuracy: 0.7481 - val_loss: 0.4869
Epoch 7/50
943/943 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - accuracy: 0.7566 - loss: 0.4702 - val_accuracy: 0.7529 - val_loss: 0.4834
Epoch 8/50
943/943 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - accuracy: 0.7624 - loss: 0.4625 - val_accuracy: 0.7491 - val_loss: 0.4903
Epoch 9/50
943/943 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.7660 - loss: 0.4611 - val_accuracy: 0.7457 - val_loss: 0.5098
Epoch 10/50
943/943 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - accuracy: 0.7678 - loss: 0.4516 - val_accuracy: 0.7454 - val_loss: 0.4926
Epoch 11/50
943/943 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - accuracy: 0.7704 - loss: 0.4464 - val_accuracy: 0.7425 - val_loss: 0.4953
Epoch 12/50
943/943 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - accuracy: 0.7778 - loss: 0.4382 - val_accuracy: 0.7401 - val_loss: 0.5084
Epoch 13/50
943/943 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.7848 - loss: 0.4284 - val_accuracy: 0.7385 - val_loss: 0.5210
Epoch 14/50
943/943 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.7813 - loss: 0.4342 - val_accuracy: 0.7335 - val_loss: 0.5060
Epoch 15/50
943/943 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - accuracy: 0.7903 - loss: 0.4237 - val_accuracy: 0.7284 - val_loss: 0.5108
Epoch 16/50
943/943 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - accuracy: 0.7924 - loss: 0.4174 - val_accuracy: 0.7278 - val_loss: 0.5327
Epoch 17/50
943/943 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - accuracy: 0.7948 - loss: 0.4081 - val_accuracy: 0.7300 - val_loss: 0.5577
Epoch 18/50
943/943 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.7992 - loss: 0.4034 - val_accuracy: 0.7261 - val_loss: 0.5473
Epoch 19/50
943/943 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - accuracy: 0.8027 - loss: 0.3968 - val_accuracy: 0.7255 - val_loss: 0.5485
Epoch 20/50
943/943 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - accuracy: 0.8069 - loss: 0.3897 - val_accuracy: 0.7274 - val_loss: 0.5730
Epoch 21/50
943/943 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.8177 - loss: 0.3776 - val_accuracy: 0.7245 - val_loss: 0.5896
Epoch 22/50
943/943 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - accuracy: 0.8160 - loss: 0.3723 - val_accuracy: 0.7169 - val_loss: 0.5857
Epoch 23/50
943/943 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - accuracy: 0.8257 - loss: 0.3624 - val_accuracy: 0.7189 - val_loss: 0.6359
Epoch 24/50
943/943 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.8345 - loss: 0.3494 - val_accuracy: 0.7100 - val_loss: 0.6182
Epoch 25/50
943/943 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - accuracy: 0.8314 - loss: 0.3519 - val_accuracy: 0.7197 - val_loss: 0.7415
Epoch 26/50
943/943 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.8378 - loss: 0.3456 - val_accuracy: 0.7038 - val_loss: 0.6834
Epoch 27/50
943/943 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - accuracy: 0.8403 - loss: 0.3363 - val_accuracy: 0.7141 - val_loss: 0.7165
Epoch 28/50
943/943 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - accuracy: 0.8461 - loss: 0.3272 - val_accuracy: 0.7138 - val_loss: 0.7114
Epoch 29/50
943/943 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - accuracy: 0.8491 - loss: 0.3194 - val_accuracy: 0.7104 - val_loss: 0.6925
Epoch 30/50
943/943 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - accuracy: 0.8551 - loss: 0.3114 - val_accuracy: 0.7093 - val_loss: 0.7771
Epoch 31/50
943/943 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.8562 - loss: 0.3035 - val_accuracy: 0.7121 - val_loss: 0.7579
Epoch 32/50
943/943 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - accuracy: 0.8579 - loss: 0.3013 - val_accuracy: 0.7131 - val_loss: 0.8622
Epoch 33/50
943/943 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - accuracy: 0.8626 - loss: 0.2949 - val_accuracy: 0.7058 - val_loss: 0.8913
Epoch 34/50
943/943 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.8665 - loss: 0.2882 - val_accuracy: 0.7070 - val_loss: 0.8618
Epoch 35/50
943/943 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - accuracy: 0.8711 - loss: 0.2783 - val_accuracy: 0.7189 - val_loss: 0.8468
Epoch 36/50
943/943 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - accuracy: 0.8719 - loss: 0.2745 - val_accuracy: 0.7117 - val_loss: 0.9005
Epoch 37/50
943/943 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - accuracy: 0.8774 - loss: 0.2666 - val_accuracy: 0.7129 - val_loss: 0.9418
Epoch 38/50
943/943 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - accuracy: 0.8753 - loss: 0.2680 - val_accuracy: 0.7062 - val_loss: 0.9794
Epoch 39/50
943/943 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - accuracy: 0.8807 - loss: 0.2616 - val_accuracy: 0.6973 - val_loss: 0.9286
Epoch 40/50
943/943 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - accuracy: 0.8848 - loss: 0.2536 - val_accuracy: 0.6949 - val_loss: 0.8818
Epoch 41/50
943/943 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - accuracy: 0.8884 - loss: 0.2467 - val_accuracy: 0.7080 - val_loss: 0.9794
Epoch 42/50
943/943 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - accuracy: 0.8859 - loss: 0.2450 - val_accuracy: 0.6994 - val_loss: 1.0231
Epoch 43/50
943/943 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - accuracy: 0.8922 - loss: 0.2386 - val_accuracy: 0.7060 - val_loss: 0.9476
Epoch 44/50
943/943 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - accuracy: 0.8918 - loss: 0.2408 - val_accuracy: 0.7026 - val_loss: 1.1498
Epoch 45/50
943/943 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - accuracy: 0.8943 - loss: 0.2344 - val_accuracy: 0.6975 - val_loss: 1.1625
Epoch 46/50
943/943 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.8979 - loss: 0.2256 - val_accuracy: 0.6941 - val_loss: 0.9787
Epoch 47/50
943/943 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.8993 - loss: 0.2246 - val_accuracy: 0.6979 - val_loss: 1.2053
Epoch 48/50
943/943 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - accuracy: 0.8997 - loss: 0.2200 - val_accuracy: 0.7039 - val_loss: 1.2316
Epoch 49/50
943/943 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - accuracy: 0.9079 - loss: 0.2094 - val_accuracy: 0.6970 - val_loss: 1.1370
Epoch 50/50
943/943 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - accuracy: 0.9068 - loss: 0.2097 - val_accuracy: 0.6934 - val_loss: 1.2066

In [18]:
loss,accuracy=model.evaluate(x,y)

1178/1178 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.9081 - loss: 0.2225

**Building Neural Network**